# define parent
FROM redhat/ubi8

# define arguments
ARG BUILD_DATE
ARG APPLICATION_VERSION
ARG REDHAT_USERNAME
ARG REDHAT_PASSWORD

# define maintainer
LABEL \
  org.label-schema.name="docker-xfce" \
  org.label-schema.version="${APPLICATION_VERSION}" \
  org.label-schema.build-data="${BUILD_DATE}"

# add application and start script
ADD rootfs.centos.8 /

# add environment variables
ENV \
  DISPLAY=:0

# register system
RUN \
  subscription-manager register --username ${REDHAT_USERNAME} --password ${REDHAT_PASSWORD}
RUN \
  subscription-manager attach
  
  # install packages
RUN \
  dnf install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
  && dnf update -y \
  && dnf groupinstall -y "Xfce" \
  && dnf groupinstall -y "Fonts" \
  && dnf install -y \
    firefox \
    gedit \
    git \
    hostname \
    java-11-openjdk-devel \
    procps-ng \
    python3 \
    python3-numpy \
    sudo \
    supervisor \
    vim \
    wget \
    wireshark \
    zip \
  && dnf clean all

RUN \
  mkdir -p /tmp/tigervnc \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-1.12.0-1.el8.x86_64.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/x86_64/tigervnc-1.12.0-1.el8.x86_64.rpm/download \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-icons-1.12.0-1.el8.noarch.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/noarch/tigervnc-icons-1.12.0-1.el8.noarch.rpm/download \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-license-1.12.0-1.el8.noarch.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/noarch/tigervnc-license-1.12.0-1.el8.noarch.rpm/download \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-server-1.12.0-1.el8.x86_64.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/x86_64/tigervnc-server-1.12.0-1.el8.x86_64.rpm/download \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-server-minimal-1.12.0-1.el8.x86_64.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/x86_64/tigervnc-server-minimal-1.12.0-1.el8.x86_64.rpm/download \
  && wget -q -O \
    /tmp/tigervnc/tigervnc-server-module-1.12.0-1.el8.x86_64.rpm \
    https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/el8/RPMS/x86_64/tigervnc-server-module-1.12.0-1.el8.x86_64.rpm/download \
  && dnf install -y /tmp/tigervnc/*.rpm \
  && rm -rf /tmp/tigervnc \
  && dnf --disableplugin=subscription-manager clean all

RUN \
  mkdir -p /opt/novnc/utils/websockify \
  && wget -qO- https://github.com/novnc/noVNC/archive/v1.3.0.tar.gz | tar xz --strip 1 -C /opt/novnc/ \
  && wget -qO- https://github.com/novnc/websockify/archive/v0.10.0.tar.gz | tar xz --strip 1 -C /opt/novnc/utils/websockify \
  && ln -s /opt/novnc/vnc.html /opt/novnc/index.html

RUN \
  rm -f /etc/xdg/autostart/xfce-polkit* \
  && rm -f /etc/xdg/autostart/xscreensaver.desktop \
  && /bin/dbus-uuidgen > /etc/machine-id \
  && echo "source /root/.bash_aliases" >> /root/.bashrc

# unregister system
RUN \
  subscription-manager unregister

# set work directory
WORKDIR /root

# entrypoint
ENTRYPOINT [ "/entrypoint.sh" ]
