# define parent
FROM quay.io/centos/centos:stream8

# define arguments
ARG BUILD_DATE
ARG APPLICATION_VERSION

# define maintainer
LABEL \
  org.label-schema.name="docker-xfce" \
  org.label-schema.version="${APPLICATION_VERSION}" \
  org.label-schema.build-data="${BUILD_DATE}"

# add application and start script
ADD rootfs.centos.8 /

# add environment variables
ENV \
  DISPLAY=:0

# install packages
RUN \
  dnf install -y \
    epel-release \
  && dnf update -y \
  && dnf groupinstall -y "Xfce" \
  && dnf groupinstall -y "Fonts" \
  && dnf install -y \
    firefox \
    gedit \
    git \
    hostname \
    java-11-openjdk-devel \
    procps-ng \
    python3 \
    python3-numpy \
    sudo \
    supervisor \
    vim \
    wget \
    wireshark \
    zip \
  && dnf clean all

RUN \
  dnf install -y \
    tigervnc \
    tigervnc-icons \
    tigervnc-license \
    tigervnc-server \
    tigervnc-server-minimal \
    tigervnc-server-module \
  && dnf clean all

RUN \
  mkdir -p /opt/novnc/utils/websockify \
  && wget -qO- https://github.com/novnc/noVNC/archive/v1.3.0.tar.gz | tar xz --strip 1 -C /opt/novnc/ \
  && wget -qO- https://github.com/novnc/websockify/archive/v0.10.0.tar.gz | tar xz --strip 1 -C /opt/novnc/utils/websockify \
  && ln -s /opt/novnc/vnc.html /opt/novnc/index.html

RUN \
  rm -f /etc/xdg/autostart/xfce-polkit* \
  && rm -f /etc/xdg/autostart/xscreensaver.desktop \
  && /bin/dbus-uuidgen > /etc/machine-id \
  && echo "source /root/.bash_aliases" >> /root/.bashrc

# expose novnc port
EXPOSE 6080

# set work directory
WORKDIR /root

# entrypoint
ENTRYPOINT [ "/entrypoint.sh" ]
